# Column Transformer
- Sometimes different columns in your data, require different king of tranformations.
- Like one columns need missing value handling, other requires ohe, one reuires lable encofing, other requores ordinal encoding.
- Doing all these separately and combining them after is very tedious. We can do all this in one line using colum

## Data collection

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('../Datasets/covid_toy.csv')

In [17]:
df.sample(5)

age  gender  fever   cough       city has_covid
57   49  Female   99.0  Strong  Bangalore        No
48   66    Male   99.0  Strong  Bangalore        No
55   81  Female  101.0    Mild     Mumbai       Yes
70   68  Female  101.0  Strong      Delhi        No
16   69  Female  103.0    Mild    Kolkata       Yes

In [18]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [19]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [20]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [21]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

You can see in the above dataset:
- 'fever' -> requires handling of missing values
- 'city','gender' -> nominal categorical data requires ohe
- 'cough' -> ordinal categorical data requires OrdinalEncoding
- 'has_covid' -> requires LabelEncoding

## Showing all transformations individually

### Train Test Split

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
df.sample(5)

age  gender  fever   cough       city has_covid
48   66    Male   99.0  Strong  Bangalore        No
57   49  Female   99.0  Strong  Bangalore        No
77    8  Female  101.0    Mild    Kolkata        No
38   49  Female  101.0    Mild      Delhi       Yes
85   16  Female  103.0    Mild  Bangalore       Yes

In [24]:
df.shape

(100, 6)

In [25]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:5],df.iloc[:,-1],test_size = 0.2, random_state = 0)

In [26]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(80, 5) (80,)
(20, 5) (20,)


### Handling missing values in 'fever'
- using SimpleImputer -> replaces missing values by the mean

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
si = SimpleImputer()

In [29]:
X_train_fever = si.fit_transform(X_train[['fever']])

In [30]:
X_train_fever.shape

(80, 1)

In [31]:
X_test_fever = si.transform(X_test[['fever']])

In [32]:
X_test_fever.shape

(20, 1)

### OHE on 'gender' and 'city'

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False, dtype = np.int32, )

In [35]:
#city -> 4 categories
#gender -> 2 categories
#after ohe:
# city -> 3columns
# gender -> 1 column
#Hence, 6 categories converted to 4 columns
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

In [36]:
X_train_gender_city.shape

(80, 4)

In [37]:
X_test_gender_city = ohe.transform(X_test[['gender','city']])

In [38]:
X_test_gender_city.shape

(20, 4)

## Ordinal Encoding on 'cough'

In [39]:
from sklearn.preprocessing import OrdinalEncoder

In [40]:
oe = OrdinalEncoder(categories = [['Mild','Strong']])

In [41]:
X_train_cough = oe.fit_transform(X_train[['cough']])

In [42]:
X_train_cough.shape

(80, 1)

In [43]:
X_test_cough = oe.transform(X_test[['cough']])

In [44]:
X_test_cough.shape

(20, 1)

## Label Encoding on 'has_covid'

In [45]:
from sklearn.preprocessing import LabelEncoder

In [46]:
le = LabelEncoder()

In [47]:
y_train_has_covid = le.fit_transform(y_train)

In [48]:
y_train_has_covid.shape

(80,)

In [49]:
y_test_has_covid = le.fit_transform(y_test)

In [50]:
y_test_has_covid.shape

(20,)

## Concating everything

In [51]:
X_train_fever

array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [52]:
X_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [53]:
X_train_gender_city

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0,

- Note: Everything is in array
- We want the original age column also in the final df.
- So first convert age column to an array

In [54]:
X_train_age = X_train.drop(columns = ['gender','city','fever','cough']).values

In [55]:
X_train_age.shape

(80, 1)

In [56]:
X_test_age = X_test.drop(columns = ['gender','city','fever','cough']).values

In [57]:
X_test_age.shape

(20, 1)

In [58]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis = 1)

In [59]:
#columns should be -> 1 age, 1 fever, 1 gender, 3 city 1 cough = 7
X_train_transformed.shape

(80, 7)

In [60]:
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis = 1)

In [61]:
X_test_transformed.shape

(20, 7)

## Using Column Transfromer

In [62]:
from sklearn.compose import ColumnTransformer

**Note:**
- Columns transformer takes the following arguments
- transformers = [('name_of_transformer','function_to_implement',['column_name'])]
- remainder -> takes two values 'passthorugh' -> which means the rest column will remain as it is and 'drop' -> drops the rest columns

In [63]:
transformer = ColumnTransformer(transformers = [('tf1',SimpleImputer(),['fever']),
                                                ('tf2',OneHotEncoder(sparse_output = False,drop = 'first',dtype = np.int32),['gender','city']),
                                                ('tf3',OrdinalEncoder(categories = [['Mild','Strong']]),['cough'])],
                                remainder = 'passthrough')

In [64]:
X_train_transformed_new = transformer.fit_transform(X_train)

In [65]:
X_train_transformed_new.shape

(80, 7)

In [66]:
X_test_transformed_new = transformer.fit_transform(X_test)

In [67]:
X_test_transformed_new.shape

(20, 7)