# Column Transformer
- Sometimes different columns in your data, require different king of tranformations.
- Like one columns need missing value handling, other requires ohe, one reuires lable encofing, other requores ordinal encoding.
- Doing all these separately and combining them after is very tedious. We can do all this in one line using colum

## Data collection

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('../Datasets/covid_toy.csv')

In [5]:
df.sample(5)

age  gender  fever   cough     city has_covid
88    5  Female  100.0    Mild  Kolkata        No
81   65    Male   99.0    Mild    Delhi        No
56   71    Male    NaN  Strong  Kolkata        No
66   51    Male  104.0    Mild  Kolkata        No
23   80  Female   98.0    Mild    Delhi       Yes

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [9]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

You can see in the above dataset:
- 'fever' -> requires handling of missing values
- 'city','gender' -> nominal categorical data requires ohe
- 'cough' -> ordinal categorical data requires OrdinalEncoding
- 'has_covid' -> requires LabelEncoding

## Showing all transformations individually

### Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
df.sample(5)

age  gender  fever   cough     city has_covid
69   73  Female  103.0    Mild    Delhi        No
22   71  Female   98.0  Strong  Kolkata       Yes
15   70    Male  103.0  Strong  Kolkata       Yes
55   81  Female  101.0    Mild   Mumbai       Yes
71   75  Female  104.0  Strong    Delhi        No

In [12]:
df.shape

(100, 6)

In [13]:
X_train,X_test,y_trainf,y_test = train_test_split(df.iloc[:,0:5],df.iloc[:,-1],test_size = 0.2, random_state = 0)

In [14]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

NameError: name 'y_train' is not defined

### Handling missing values in 'fever'
- using SimpleImputer -> replaces missing values by the mean

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si = SimpleImputer()

In [ ]:
X_train_fever = si.fit_transform(X_train[['fever']])

In [ ]:
X_train_fever.shape

(80, 1)

In [ ]:
X_test_fever = si.transform(X_test[['fever']])

In [ ]:
X_test_fever.shape

(20, 1)

### OHE on 'gender' and 'city'

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False, dtype = np.int32, )

In [ ]:
#city -> 4 categories
#gender -> 2 categories
#after ohe:
# city -> 3columns
# gender -> 1 column
#Hence, 6 categories converted to 4 columns
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

In [ ]:
X_train_gender_city.shape

(80, 4)

In [ ]:
X_test_gender_city = ohe.transform(X_test[['gender','city']])

In [ ]:
X_test_gender_city.shape

(20, 4)

## Ordinal Encoding on 'cough'

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories = [['Mild','Strong']])

In [ ]:
X_train_cough = oe.fit_transform(X_train[['cough']])

In [ ]:
X_train_cough.shape

(80, 1)

In [ ]:
X_test_cough = oe.transform(X_test[['cough']])

In [ ]:
X_test_cough.shape

(20, 1)

## Label Encoding on 'has_covid'

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
y_train_has_covid = le.fit_transform(y_train)

In [ ]:
y_train_has_covid.shape

(80,)

In [ ]:
y_test_has_covid = le.fit_transform(y_test)

In [ ]:
y_test_has_covid.shape

(20,)

## Concating everything

In [ ]:
X_train_fever

array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [ ]:
X_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [ ]:
X_train_gender_city

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0,

- Note: Everything is in array
- We want the original age column also in the final df.
- So first convert age column to an array

In [ ]:
X_train_age = X_train.drop(columns = ['gender','city','fever','cough']).values

In [ ]:
X_train_age.shape

(80, 1)

In [ ]:
X_test_age = X_test.drop(columns = ['gender','city','fever','cough']).values

In [ ]:
X_test_age.shape

(20, 1)

In [ ]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis = 1)

(80, 1) (80, 1) (80, 4) (80, 1)


In [ ]:
#columns should be -> 1 age, 1 fever, 1 gender, 3 city 1 cough = 7
X_train_transformed.shape

(80, 7)

In [ ]:
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis = 1)

In [ ]:
X_test_transformed.shape

(20, 7)

## Using Column Transfromer

In [ ]:
from sklearn.compose import ColumnTransformer

**Note:**
- Columns transformer takes the following arguments
- transformers = [('name_of_transformer','function_to_implement',['column_name'])]
- remainder -> takes two values 'passthorugh' -> which means the rest column will remain as it is and 'drop' -> drops the rest columns

In [ ]:
transformer = ColumnTransformer(transformers = [('tf1',SimpleImputer(),['fever']),
                                                ('tf2',OneHotEncoder(sparse_output = False,drop = 'first',dtype = np.int32),['gender','city']),
                                                ('tf3',OrdinalEncoder(categories = [['Mild','Strong']]),['cough'])],
                                remainder = 'passthrough')

In [ ]:
X_train_transformed_new = transformer.fit_transform(X_train)

In [ ]:
X_train_transformed_new.shape

(80, 7)

In [ ]:
X_test_transformed_new = transformer.fit_transform(X_test)

In [ ]:
X_test_transformed_new.shape

(20, 7)